export const FETCH_TRENDING_GIFS_INITIATED = 'gifs/FETCH_TRENDING_GIFS_INITIATED';
export const FETCH_TRENDING_GIFS_FINISHED = 'gifs/FETCH_TRENDING_GIFS_FINISHED';

export const FETCH_TRENDING_GIFS_NEXT_PAGE_INITIATED = 'gifs/FETCH_TRENDING_GIFS_NEXT_PAGE_INITIATED';
export const FETCH_TRENDING_GIFS_NEXT_PAGE_FINISHED = 'gifs/FETCH_TRENDING_GIFS_NEXT_PAGE_FINISHED';

export const SET_GIF_FAVORITE_STATUS = 'gifs/SET_GIF_FAVORITE_STATUS';

export const AFTER_REHYDRATE = 'gifs/AFTER_REHYDRATE';
